### ISSUE TITLE
potential bug in `make-schedule.py`

### ISSUE THREAD

**Issue by whuangum** [emeryberger/COMPSCI-630#36]
https://github.com/emeryberger/COMPSCI-630/blob/master/make-schedule.py#L84 is not handling [nextyear](https://github.com/emeryberger/COMPSCI-630/blob/master/schedule.csv#L6). One might call this a feature.

**Comment by emeryberger** [comment]
Fixed, thanks!

**Comment by emeryberger** [comment]
fixed, thanks!

--
Professor Emery Berger
College of Information and Computer Sciences
University of Massachusetts Amherst
www.emeryberger.org, @emeryberger
